first pass at updating my zshrc with plugins

diff --git a/.dotfiles/dots/work/zshrc b/.dotfiles/dots/work/zshrc
--- a/.dotfiles/dots/work/zshrc
+++ b/.dotfiles/dots/work/zshrc
@@ -134,6 +134,85 @@ POWERLEVEL9K_ANACONDA_RIGHT_DELIMITER=""
 POWERLEVEL9K_ANACONDA_BACKGROUND='cyan'
 POWERLEVEL9K_ANACONDA_FOREGROUND='black'
 
+
+# dumb terminal can be a vim dump terminal in that case don't try to load plugins
+if [ ! $TERM = dumb ]; then
+    ZGEN_AUTOLOAD_COMPINIT=true
+    # If user is root it can have some issues with access to competition files
+    if [[ "${USER}" == "root" ]]; then
+        ZGEN_AUTOLOAD_COMPINIT=false
+    fi
+
+    # load zgen
+    source $DOTFILES/zgen/zgen.zsh
+
+    # configure zgen
+    if ! zgen saved; then
+
+        # zgen will load oh-my-zsh and download it if required
+        zgen oh-my-zsh
+
+        # these plugins only have utility on my raspis
+        if ! [[ `uname` = 'Darwin' ]]
+            zgen oh-my-zsh plugins/debian
+            zgen oh-my-zsh plugins/systemd
+        fi
+
+        # list of plugins from zsh I use
+        # see https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins
+        zgen oh-my-zsh plugins/brew
+        zgen oh-my-zsh plugins/docker
+        zgen oh-my-zsh plugins/git
+        zgen oh-my-zsh plugins/git-extras
+        zgen oh-my-zsh plugins/gitignore
+        zgen oh-my-zsh plugins/osx
+        zgen oh-my-zsh plugins/pip
+        zgen oh-my-zsh plugins/python
+        zgen oh-my-zsh plugins/sudo
+        zgen oh-my-zsh plugins/tmuxinator
+        zgen oh-my-zsh plugins/vundle
+        zgen oh-my-zsh plugins/autojump
+        zgen oh-my-zsh plugins/autopep8
+        zgen oh-my-zsh plugins/django
+        zgen oh-my-zsh plugins/extract
+        zgen oh-my-zsh plugins/gitflow
+        zgen oh-my-zsh plugins/jsontools
+        zgen oh-my-zsh plugins/macports
+        zgen oh-my-zsh plugins/pep8
+        zgen oh-my-zsh plugins/pyenv
+        zgen oh-my-zsh plugins/pylint
+        zgen oh-my-zsh plugins/taskwarrior
+        zgen oh-my-zsh plugins/vi-mode
+
+        # https://github.com/Tarrasch/zsh-autoenv
+        zgen load Tarrasch/zsh-autoenv
+        # https://github.com/zsh-users/zsh-completions
+        zgen load zsh-users/zsh-completions src
+        
+        # my own plugins
+        zgen load $DOTFILES/plugins/aliases
+        zgen load $DOTFILES/plugins/dotfiles
+        zgen load $DOTFILES/plugins/my-brew
+        zgen load $DOTFILES/plugins/tpm
+
+        # load https://github.com/bhilburn/powerlevel9k theme for zsh
+        zgen load bhilburn/powerlevel9k powerlevel9k.zsh-theme
+
+        # It takes control, so load last
+        zgen load $DOTFILES/plugins/my-tmux
+
+        zgen save
+    fi
+
+    # Configure vundle
+    vundle-init
+fi
+
+# specific for machine configuration, which I don't sync
+if [ -f ~/.machinerc ]; then
+    source ~/.machinerc
+fi
+
 alias zshconfig="code ~/.zshrc"
 alias ohmyzsh="code ~/.oh-my-zsh"
 alias dotfiles="git --git-dir=$HOME/.dotfiles.git"
@@ -162,6 +241,23 @@ unset __conda_setup
 # <<< conda initialize <<<
 
 test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
+
+# additional configuration for zsh
+# Remove the history (fc -l) command from the history list when invoked.
+setopt histnostore
+# Remove superfluous blanks from each command line being added to the history list.
+setopt histreduceblanks
+# Do not exit on end-of-file. Require the use of exit or logout instead.
+# setopt ignoreeof
+# Print the exit value of programs with non-zero exit status.
+setopt printexitvalue
+# Do not share history
+setopt no_share_history
+
+# if profiling was on
+if $PROFILING; then
+    zprof
+fi
 
 # zsh-syntax-highlighting must be sourced as the last thing in this file
 source ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
